### ISSUE TITLE
FAQ duplicate

### ISSUE THREAD

**Issue by alexuribe** [hellopearlcare/issues#3]
### Please mark with an *x* the box that best describes your request:
- [X] Report a bug
- [ ] I want help
- [ ] I have a question
- [ ] I want to propose an enhancement
- [ ] I have a new-feature request

On the FAQ, "What health professionals are on Pearl?" appears twice with two different answers. The correct answer is "Pearl is focused on oral health and dentistry."

**Comment by jolares** [comment]
Thanks. The issue has been solved and will be rolled out to production soon.
